[workspace]
default-members = ["crates/ddns_reporter"]
resolver = "2"
members = ["crates/*", "xtask"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
tokio = { version = "1.51.0", features = ["rt", "rt-multi-thread", "macros"] }
futures = "0.3.32"
netwatcher = { version = "0.4.1" }
reqwest = { version = "0.13.2", features = ["json"] }
serde_json = "1.0.149"
config = "0.15.22"
serde = { version = "1.0.228", features = ["derive"] }
async-trait = "0.1.89"
thiserror = "2.0.18"
scopeguard = "1.2.0"

clap = { version = "4.6.0", features = ["derive"] }

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
    "env-filter",
    "fmt",
    "time",
] }
tracing-appender = "0.2.4"
time = { version = "0.3.47", features = ["formatting", "macros"] }
rxrust = { version = "0.15.0", features = ["tokio-scheduler"] }

windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_Ndis",
] }

# The versions of rtnetlink and netlink-packet-route must match.
rtnetlink = "0.20.0"
netlink-packet-route = "0.28.0"
