[package]
name = "ddns_reporter"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
if-watch = { version = "3", features = ["smol"] }
futures = "0.3.31"
reqwest = { version = "0", features = ["json"] }
serde_json = "1"
thiserror = "1"
config = "0"
serde = { version = "1", features = ["derive"] }
